=== amh38/XML/team06/we-challenge/ressources/validation/data.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="wgchallenge">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="user" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>

                    <xs:key name="userkey">
                        <xs:selector xpath="user"/>
                        <xs:field xpath="username"/>
                    </xs:key>
                    <xs:keyref name="ownerkeyref" refer="userkey">
                        <xs:selector xpath="wgchallenge/events/event"/>
                        <xs:field xpath="owner"/>
                    </xs:keyref>
                    <xs:keyref name="memberkeyref" refer="userkey">
                        <xs:selector xpath="wgchallenge/events/event/members/member"/>
                        <xs:field xpath="name"/>
                    </xs:keyref>
                </xs:element>
                <xs:element name="events">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="event" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                    <xs:key name="eventID">
                        <xs:selector xpath="event"/>
                        <xs:field xpath="@id"/>
                    </xs:key>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="user">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="username" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="countResidents" type="residentType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="clothesWasher" type="booleanUndefined" minOccurs="1" maxOccurs="1"/>
                <xs:element name="dishwasher" type="booleanUndefined" minOccurs="1" maxOccurs="1"/>
                <xs:element name="location" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="profilePicture" type="xs:string" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="type" type="typeType" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="event">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="name"/>
                <xs:element type="xs:date" name="startdate"/>
                <xs:element type="xs:date" name="enddate"/>
                <xs:element type="xs:positiveInteger" name="minResidents"/>
				<xs:element type="booleanUndefined" name="reqCW"/>
				<xs:element type="booleanUndefined" name="reqDW"/>
				<xs:element type="xs:string" name="description"/>
				<xs:element type="xs:string" name="owner" minOccurs="1" maxOccurs="1"/>
                <xs:element type="membersType" name="members"/>
            </xs:sequence>
            <xs:attribute type="xs:positiveInteger" name="id"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="empty">
        <xs:restriction base="xs:string">
            <xs:enumeration value=" "/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="residentType">
        <xs:restriction base="xs:byte">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="WG"/>
            <xs:enumeration value="Firma"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="booleanUndefined">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
            <xs:enumeration value="undefined"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="membersType">
        <xs:sequence minOccurs="0" maxOccurs="unbounded">

			<xs:element name="member">
				<xs:complexType>
					<xs:sequence>
						<xs:element type="xs:string" name="name"/>
						<xs:element	type="xs:string" name="eventpic"/>
                        <xs:element type="xs:integer" name="totalVotes"/>
                        <xs:element type="xs:integer" name="positiveVotes"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== amh38/XML/team06/we-challenge/ressources/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<wgchallenge xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validation/data.xsd">
	<users>
		<user type="WG">
			<username>testWG</username>
			<countResidents>3</countResidents>
			<clothesWasher>false</clothesWasher>
			<dishwasher>true</dishwasher>
			<location>Zurich</location>
			<profilePicture>../ressources/profile_pictures/testWG.png</profilePicture>
		</user>
		<user type="Firma">
			<username>testFirma</username>
			<countResidents>0</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>Zurich</location>
			<profilePicture>../ressources/profile_pictures/testFirma.jpg</profilePicture>
		</user>
		<user type="WG">
			<username>1234</username>
			<countResidents>5</countResidents>
			<clothesWasher>false</clothesWasher>
			<dishwasher>false</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="WG">
			<username>testWGawdawd</username>
			<countResidents>0</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="WG">
			<username>testWGawdawdasdadwad</username>
			<countResidents>0</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="Firma">
			<username>testComp</username>
			<countResidents>0</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="WG">
			<username>testWG2</username>
			<countResidents>0</countResidents>
			<clothesWasher>false</clothesWasher>
			<dishwasher>true</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="Firma">
			<username>stefkueng</username>
			<countResidents>0</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
		<user type="WG">
			<username>ste</username>
			<countResidents>2</countResidents>
			<clothesWasher>undefined</clothesWasher>
			<dishwasher>undefined</dishwasher>
			<location>undefined</location>
			<profilePicture>undefined</profilePicture>
		</user>
	</users>
	<events>
		<event id="1">
			<name>TestEvent</name>
			<startdate>2019-01-01</startdate>
			<enddate>2019-01-02</enddate>
			<minResidents>2</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>testDescription</description>
			<owner>testFirma</owner>
			<members>
				<member>
					<name>testWG</name>
					<eventpic/>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
				<member>
					<name>testWGawdawd</name>
					<eventpic/>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
				<member>
					<name>ste</name>
					<eventpic>../ressources/participant_pictures/1_ste.jpg</eventpic>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
				<member>
					<name>ste</name>
					<eventpic>../ressources/participant_pictures/1_ste.jpg</eventpic>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
			</members>
		</event>
		<event id="2">
			<name>TestEvent2</name>
			<startdate>2019-01-01</startdate>
			<enddate>2019-01-02</enddate>
			<minResidents>2</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>testDescription</description>
			<owner>testFirma</owner>
			<members>
				<member>
					<name>testWGawdawd</name>
					<eventpic/>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
			</members>
		</event>
		<event id="3">
			<name>TestEvent3</name>
			<startdate>2019-01-01</startdate>
			<enddate>2019-01-02</enddate>
			<minResidents>2</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>testDescription</description>
			<owner>testComp</owner>
			<members>
				<member>
					<name>123</name>
					<eventpic/>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
				<member>
					<name>ste</name>
					<eventpic>../ressources/participant_pictures/3_ste.jpg</eventpic>
					<totalVotes>0</totalVotes>
					<positiveVotes>0</positiveVotes>
				</member>
			</members>
		</event>
		<event id="4">
			<name>stefan</name>
			<startdate>2019-03-07</startdate>
			<enddate>2019-03-13</enddate>
			<minResidents>3</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>Stef</description>
			<owner>testFirma</owner>
			<members/>
		</event>
		<event id="5">
			<name>awd</name>
			<startdate>2019-02-27</startdate>
			<enddate>2019-03-23</enddate>
			<minResidents>3</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>1</description>
			<owner>stefkueng</owner>
			<members/>
		</event>
		<event id="6">
			<name>awd</name>
			<startdate>2019-02-27</startdate>
			<enddate>2019-03-23</enddate>
			<minResidents>3</minResidents>
			<reqCW>false</reqCW>
			<reqDW>false</reqDW>
			<description>1</description>
			<owner>stefkueng</owner>
			<members/>
		</event>
	</events>
</wgchallenge>
